window.APP_CONFIG = {
  SUPABASE_URL: "https://objzavshpyhndvbdgrzk.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ianphdnNocHlobmR2YmRncnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1NDAyNDIsImV4cCI6MjA5OTExNjI0Mn0.M2adyvUFEEAkB148s6uhrLyYp8kUICWuM1CJQa22RfI"
};
